name: Lerna publish

"on":
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npx lerna publish from-package -y
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
